// GENERATED by scripts/generate-colony-tiles.mjs — do not edit by hand.
// Colony tiles extracted from the reference implementation's src/server/colonies.
// 12 tiles. Each trade track has 7 steps; the marker starts at 1.

export const COLONY_TILES = [
  {
    "id": "callisto",
    "name": "カリスト",
    "englishName": "Callisto",
    "build": {
      "description": "Gain 1 energy production",
      "type": "GAIN_PRODUCTION",
      "resource": "energy"
    },
    "trade": {
      "description": "Gain n energy",
      "type": "GAIN_RESOURCES",
      "resource": "energy",
      "quantity": [
        0,
        2,
        3,
        5,
        7,
        10,
        13
      ]
    },
    "colony": {
      "description": "Gain 3 energy",
      "type": "GAIN_RESOURCES",
      "resource": "energy",
      "quantity": 3
    }
  },
  {
    "id": "ceres",
    "name": "セレス",
    "englishName": "Ceres",
    "build": {
      "description": "Gain 1 steel production",
      "type": "GAIN_PRODUCTION",
      "resource": "steel"
    },
    "trade": {
      "description": "Gain n steel",
      "type": "GAIN_RESOURCES",
      "resource": "steel",
      "quantity": [
        1,
        2,
        3,
        4,
        6,
        8,
        10
      ]
    },
    "colony": {
      "description": "Gain 2 steel",
      "type": "GAIN_RESOURCES",
      "resource": "steel",
      "quantity": 2
    }
  },
  {
    "id": "deimos",
    "name": "デイモス",
    "englishName": "Deimos",
    "build": {
      "description": "Place a hazard tile next to no other tile",
      "type": "PLACE_HAZARD_TILE",
      "quantity": [
        3,
        3,
        3
      ]
    },
    "trade": {
      "description": "Erode n spaces adjacent to hazard tiles (gaining placement bonuses)",
      "type": "ERODE_SPACES_ADJACENT_TO_HAZARDS",
      "quantity": [
        0,
        0,
        1,
        1,
        2,
        2,
        3
      ]
    },
    "colony": {
      "description": "Gain 1 M€ per hazard tile on Mars",
      "type": "GAIN_MC_PER_HAZARD_TILE"
    }
  },
  {
    "id": "enceladus",
    "name": "エンケラドゥス",
    "englishName": "Enceladus",
    "build": {
      "description": "Add 3 microbes to ANY card",
      "type": "ADD_RESOURCES_TO_CARD",
      "quantity": [
        3,
        3,
        3
      ]
    },
    "trade": {
      "description": "Add n microbes to ANY card",
      "type": "ADD_RESOURCES_TO_CARD",
      "quantity": [
        0,
        1,
        2,
        3,
        4,
        4,
        5
      ]
    },
    "colony": {
      "description": "Add 1 microbe to ANY card",
      "type": "ADD_RESOURCES_TO_CARD"
    }
  },
  {
    "id": "europa",
    "name": "エウロパ",
    "englishName": "Europa",
    "build": {
      "description": "Place an ocean tile",
      "type": "PLACE_OCEAN_TILE"
    },
    "trade": {
      "description": "Gain 1 unit of production of the type under the track marker",
      "type": "GAIN_PRODUCTION",
      "resourceTrack": [
        "mc",
        "mc",
        "energy",
        "energy",
        "plants",
        "plants",
        "plants"
      ]
    },
    "colony": {
      "description": "Gain 1 M€",
      "type": "GAIN_RESOURCES",
      "resource": "mc"
    }
  },
  {
    "id": "ganymede",
    "name": "ガニメデ",
    "englishName": "Ganymede",
    "build": {
      "description": "Gain 1 plant production",
      "type": "GAIN_PRODUCTION",
      "resource": "plants"
    },
    "trade": {
      "description": "Gain n plants",
      "type": "GAIN_RESOURCES",
      "resource": "plants",
      "quantity": [
        0,
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    "colony": {
      "description": "Gain 1 plant",
      "type": "GAIN_RESOURCES",
      "resource": "plants"
    }
  },
  {
    "id": "io",
    "name": "イオ",
    "englishName": "Io",
    "build": {
      "description": "Gain 1 heat production",
      "type": "GAIN_PRODUCTION",
      "resource": "heat"
    },
    "trade": {
      "description": "Gain n heat",
      "type": "GAIN_RESOURCES",
      "resource": "heat",
      "quantity": [
        2,
        3,
        4,
        6,
        8,
        10,
        13
      ]
    },
    "colony": {
      "description": "Gain 2 heat",
      "type": "GAIN_RESOURCES",
      "resource": "heat",
      "quantity": 2
    }
  },
  {
    "id": "luna",
    "name": "ルナ",
    "englishName": "Luna",
    "build": {
      "description": "Gain 2 M€ production",
      "type": "GAIN_PRODUCTION",
      "resource": "mc",
      "quantity": [
        2,
        2,
        2
      ]
    },
    "trade": {
      "description": "Gain n M€",
      "type": "GAIN_RESOURCES",
      "resource": "mc",
      "quantity": [
        1,
        2,
        4,
        7,
        10,
        13,
        17
      ]
    },
    "colony": {
      "description": "Gain 2 M€",
      "type": "GAIN_RESOURCES",
      "resource": "mc",
      "quantity": 2
    }
  },
  {
    "id": "miranda",
    "name": "ミランダ",
    "englishName": "Miranda",
    "build": {
      "description": "Add 1 animal to ANY card",
      "type": "ADD_RESOURCES_TO_CARD"
    },
    "trade": {
      "description": "Add n animals to ANY card",
      "type": "ADD_RESOURCES_TO_CARD",
      "quantity": [
        0,
        1,
        1,
        2,
        2,
        3,
        3
      ]
    },
    "colony": {
      "description": "Draw 1 card",
      "type": "DRAW_CARDS"
    }
  },
  {
    "id": "pluto",
    "name": "プルート",
    "englishName": "Pluto",
    "build": {
      "description": "Draw 2 cards",
      "type": "DRAW_CARDS",
      "quantity": [
        2,
        2,
        2
      ]
    },
    "trade": {
      "description": "Draw n cards",
      "type": "DRAW_CARDS",
      "quantity": [
        0,
        1,
        2,
        2,
        3,
        3,
        4
      ]
    },
    "colony": {
      "description": "Draw 1 card and then discard 1 card",
      "type": "DRAW_CARDS_AND_DISCARD_ONE"
    }
  },
  {
    "id": "titan",
    "name": "タイタン",
    "englishName": "Titan",
    "build": {
      "description": "Add 3 floaters to ANY card",
      "type": "ADD_RESOURCES_TO_CARD",
      "quantity": [
        3,
        3,
        3
      ]
    },
    "trade": {
      "description": "Add n floaters to ANY card",
      "type": "ADD_RESOURCES_TO_CARD",
      "quantity": [
        0,
        1,
        1,
        2,
        3,
        3,
        4
      ]
    },
    "colony": {
      "description": "Add 1 floater to ANY card",
      "type": "ADD_RESOURCES_TO_CARD"
    }
  },
  {
    "id": "triton",
    "name": "トリトン",
    "englishName": "Triton",
    "build": {
      "description": "Gain 3 titanium",
      "type": "GAIN_RESOURCES",
      "resource": "titanium",
      "quantity": [
        3,
        3,
        3
      ]
    },
    "trade": {
      "description": "Gain n titanium",
      "type": "GAIN_RESOURCES",
      "resource": "titanium",
      "quantity": [
        0,
        1,
        1,
        2,
        3,
        4,
        5
      ]
    },
    "colony": {
      "description": "Gain 1 titanium",
      "type": "GAIN_RESOURCES",
      "resource": "titanium"
    }
  }
];

export function getColonyTile(id) {
  return COLONY_TILES.find(tile => tile.id === id);
}
