// Japanese effect text for cards whose wording the rule-based translator in
// generate-japanese-text.mjs cannot reach. These are one-off phrasings where a
// rule per card would buy nothing over writing the sentence out.
// 339 entries.

export const CURATED_JAPANESE_EFFECTS = {
  "card-prelude2-world-government-advisor": "アクション: 気温・酸素・金星のいずれかを1段階上げる（TRは得られない）。",
  "card-venus-thermophiles": "アクション: このカードの微生物2個を支払って金星を1段階上げる、または金星タグを持つカードに微生物を1個置く。",
  "card-venus-sulphur-eating-bacteria": "アクション: このカードの微生物を支払い、1個につきMCを3獲得する、またはこのカードに微生物を1個置く。",
  "card-promo-weather-balloons": "アクション: このカードのフローター1個を支払い、火星上の都市1枚につきMCを1獲得する、またはこのカードにフローターを1個置く。",
  "card-colonies-red-spot-observatory": "アクション: このカードのフローター1個を支払ってカードを1枚引く、またはこのカードにフローターを1個置く。",
  "card-colonies-jupiter-floating-station": "アクション: ジョビアンタグを持つカードにフローターを1個置く、またはこのカードのフローター1個につきMCを1獲得する（最大4）。",
  "card-colonies-atmo-collectors": "アクション: このカードのフローター1個を取り除いてチタン2、エネルギー3、熱4のいずれかを獲得する、またはこのカードにフローターを1個置く。",
  "card-base-nitrite-reducing-bacteria": "アクション: このカードの微生物3個を取り除いてTR+1、またはこのカードに微生物を1個置く。",
  "card-base-ghg-producing-bacteria": "アクション: このカードの微生物2個を取り除いて気温を1段階上げる、またはこのカードに微生物を1個置く。",
  "card-base-extreme-cold-fungus": "アクション: 他のカードに微生物を2個置く、または植物を1獲得する。",
  "card-prelude2-space-lanes": "チタン3を獲得。効果: ジョビアンタグ・地球タグ・金星タグを持つカードのコストが、それぞれMC2下がる。",
  "card-base-anti-gravity-technology": "科学タグ7枚以上が必要。効果: カードのコストがMC2下がる。",
  "card-base-ants": "酸素4%以上が必要。アクション: このカードに微生物を1個置く。",
  "card-base-business-network": "MC生産量-1。アクション: カードを1枚購入する。",
  "card-base-caretaker-contract": "気温0°C以上が必要。アクション: 熱を8支払い、TR+1。",
  "card-base-fish": "気温2°C以上が必要。任意のプレイヤーの植物生産量-1。アクション: このカードに動物を1個置く。",
  "card-base-livestock": "酸素9%以上が必要。植物生産量-1、MC生産量+2。アクション: このカードに動物を1個置く。",
  "card-base-mass-converter": "科学タグ5枚以上が必要。エネルギー生産量+6。効果: 宇宙タグ1つにつき、カードのコストがMC2下がる。",
  "card-base-predators": "酸素11%以上が必要。アクション: このカードに動物を1個置く。",
  "card-base-quantum-extractor": "科学タグ4枚以上が必要。エネルギー生産量+4。効果: 宇宙タグを持つカードのコストがMC2下がる。",
  "card-base-restricted-area": "このタイルを置く。アクション: MCを2支払い、カードを1枚引く。",
  "card-base-shuttles": "酸素5%以上が必要。エネルギー生産量-1、MC生産量+2。効果: 宇宙タグを持つカードのコストがMC2下がる。",
  "card-base-small-animals": "酸素6%以上が必要。任意のプレイヤーの植物生産量-1。アクション: このカードに動物を1個置く。",
  "card-base-space-elevator": "チタン生産量+1。アクション: 建材を1支払い、MCを5獲得。",
  "card-base-symbiotic-fungus": "気温-14°C以上が必要。アクション: 任意のカードに微生物を1個置く。",
  "card-base-water-splitting-plant": "海洋2枚以上が必要。アクション: エネルギーを3支払い、酸素を1段階上げる。",
  "card-colonies-jovian-lanterns": "ジョビアンタグ1枚以上が必要。TR+1。任意のカードにフローターを2個置く。アクション: チタンを1支払い、このカードにフローターを2個置く。",
  "card-colonies-sky-docks": "地球タグ2枚以上が必要。交易船を1隻獲得。効果: カードのコストがMC1下がる。",
  "card-colonies-warp-drive": "科学タグ5枚以上が必要。効果: 宇宙タグを持つカードのコストがMC4下がる。",
  "card-promo-orbital-cleanup": "MC生産量-2。アクション: MCを1獲得。",
  "card-promo-penguins": "海洋8枚以上が必要。アクション: このカードに動物を1個置く。",
  "card-promo-red-ships": "酸素4%以上が必要。アクション: MCを1獲得。",
  "card-promo-solar-logistics": "チタン2を獲得。効果: 地球タグを持つカードのコストがMC2下がる。",
  "card-promo-sub-crust-measurements": "科学タグ2枚以上が必要。アクション: カードを1枚引く。",
  "card-promo-teslaract": "TR+1。アクション: エネルギー生産量+-1、植物生産量+1。",
  "card-venus-extremophiles": "科学タグ2枚以上が必要。アクション: 任意のカードに微生物を1個置く。",
  "card-venus-floating-habs": "科学タグ2枚以上が必要。アクション: MCを2支払い、任意のカードにフローターを1個置く。",
  "card-venus-maxwell-base": "金星12%以上が必要。エネルギー生産量-1。予約マスに都市タイルを1枚置く。アクション: 任意のカードにundefinedを1個置く。",
  "card-venus-stratopolis": "科学タグ2枚以上が必要。MC生産量+2。予約マスに都市タイルを1枚置く。アクション: 任意のカードにフローターを2個置く。",
  "card-venus-venus-magnetizer": "金星10%以上が必要。アクション: エネルギー生産量+-1、金星を1段階上げる。",
  "card-venus-venusian-insects": "金星12%以上が必要。アクション: このカードに微生物を1個置く。",
  "card-colonies-stormcraft-incorporated": "初期資金 48 MC。アクション: 任意のカードにフローターを1個置く。",
  "corp-cheung-shing": "効果: 建材タグを持つカードのコストがMC2下がる。",
  "p-ai-central": "科学タグ3枚以上が必要。エネルギー生産量-1。アクション: カードを2枚引く。",
  "p-asteroid": "気温を1段階上げ、チタンを2獲得。任意のプレイヤーの植物を最大3個取り除く。",
  "p-big-asteroid": "気温を2段階上げ、チタンを4獲得。任意のプレイヤーの植物を最大4個取り除く。",
  "p-capital": "海洋タイル4枚以上が必要。このタイルを置く。エネルギー生産量-2、MC生産量+5。",
  "p-comet": "気温を1段階上げ、海洋タイルを1枚置く。任意のプレイヤーの植物を最大3個取り除く。",
  "p-geothermal-power": "エネルギー生産量+2。",
  "p-giant-ice-asteroid": "気温を2段階上げ、海洋タイルを2枚置く。任意のプレイヤーの植物を最大6個取り除く。",
  "p-greenhouses": "場にある都市タイル1枚につき植物を1獲得。",
  "p-ice-asteroid": "海洋タイルを2枚置く。",
  "p-lichen": "気温-24°C以上が必要。植物生産量+1。",
  "p-mars-university": "効果: このカードを含め、科学タグを持つカードをプレイした際、手札を1枚捨てて、カードを1枚引いてもよい。",
  "p-mine": "建材生産量+1。",
  "p-moss": "海洋タイル3枚以上と植物1個の支払いが必要。植物生産量+1。",
  "p-plantation": "科学タグ2枚以上が必要。緑地タイルを1枚置き、酸素を1段階上げる。",
  "p-power-plant": "エネルギー生産量+1。",
  "p-search-for-life": "酸素6%以下であること。アクション: MCを1支払い、山札の一番上のカードを公開する。そのカードが微生物タグを持つ場合、このカードに科学資源を1個置く。ここに科学資源が1個以上あれば3点。",
  "p-solar-power": "エネルギー生産量+1。",
  "p-steelworks": "アクション: エネルギーを4支払い、建材を2獲得し、酸素を1段階上げる。",
  "p-titanium-mine": "チタン生産量+1。",
  "card-base-advanced-ecosystems": "植物タグ、微生物タグ、動物タグが必要。",
  "card-base-algae": "海洋タイル5枚以上が必要。植物を1獲得し、植物生産量+2。",
  "card-base-arctic-algae": "気温-12度以下でなければプレイできない。植物を1獲得。効果: 誰かが海洋タイルを配置するたびに、植物を2獲得する。",
  "card-base-artificial-lake": "気温-6度以上が必要。海洋タイル用に予約されていない場所に海洋タイルを1枚置く。",
  "card-base-artificial-photosynthesis": "植物生産量+1、またはエネルギー生産量+2。",
  "card-base-asteroid-mining-consortium": "自分がチタン生産量を持っていることが必要。任意のプレイヤーのチタン生産量-1、自分のチタン生産量+1。",
  "card-base-beam-from-a-thorium-asteroid": "ジョビアンタグが必要。熱生産量+3、エネルギー生産量+3。",
  "card-base-biomass-combustors": "酸素6%以上が必要。任意のプレイヤーの植物生産量-1、自分のエネルギー生産量+2。",
  "card-base-birds": "アクション: このカードに動物を1つ追加する。",
  "card-base-business-contacts": "山札の上から4枚を見る。そのうち2枚を手札に加え、残りの2枚を捨てる。",
  "card-base-ceo-s-favorite-project": "資源が1つ以上置かれているカードに資源を1つ追加する。",
  "card-base-cloud-seeding": "海洋タイル3枚以上が必要。MC生産量-1、任意のプレイヤーの熱生産量-1。植物生産量+2。",
  "card-base-convoy-from-europa": "海洋タイルを1枚置き、カードを1枚引く。",
  "card-base-development-center": "アクション: エネルギーを1消費してカードを1枚引く。",
  "card-base-dust-seals": "海洋タイル3枚以下が必要。",
  "card-base-earth-catapult": "効果: カードをプレイする際、コストが2MC安くなる。",
  "card-base-ecological-zone": "効果: このカードを含め、動物タグまたは植物タグを持つカードをプレイした際、このカードに動物を1つ追加する。自分が緑地タイルを持っていることが必要。このタイルは任意の緑地タイルに隣接させて置く。",
  "card-base-electro-catapult": "アクション: 植物1、または建材1を消費してMCを7獲得。",
  "card-base-energy-saving": "場にある都市タイル1枚につき、エネルギー生産量+1。",
  "card-base-eos-chasma-national-park": "気温-12度以上が必要。任意の動物カードに動物を1つ追加する。植物を3獲得。MC生産量+2。",
  "card-base-equatorial-magnetizer": "アクション: エネルギー生産量-1と引き換えにTR+1。",
  "card-base-farming": "気温+4度以上が必要。MC生産量+2、植物生産量+2。植物を2獲得。",
  "card-base-flooding": "海洋タイルを1枚置く。このタイルに隣接するタイルがある場合、そのタイルの所有者の1人から4MCを取り除いてもよい。",
  "card-base-fuel-factory": "エネルギー生産量-1、チタン生産量+1、MC生産量+1。",
  "card-base-great-escarpment-consortium": "自分が建材生産量を持っていることが必要。任意のプレイヤーの建材生産量-1、自分の建材生産量+1。",
  "card-base-hackers": "エネルギー生産量-1、任意のプレイヤーのMC生産量-2。自分のMC生産量+2。",
  "card-base-heat-trappers": "任意のプレイヤーの熱生産量-2、自分のエネルギー生産量+1。",
  "card-base-herbivores": "酸素8%以上が必要。このカードに動物を1つ追加する。任意のプレイヤーの植物生産量-1。",
  "card-base-hired-raiders": "任意のプレイヤーから建材を最大2、またはMCを3奪う。",
  "card-base-immigrant-city": "エネルギー生産量-1、MC生産量-2。都市タイルを1枚置く。",
  "card-base-imported-hydrogen": "植物を3獲得、または他のカードに微生物を3か動物を2追加する。海洋タイルを1枚置く。",
  "card-base-imported-nitrogen": "TR+1、植物を4獲得。他のカードに微生物を3、他のカードに動物を2追加する。",
  "card-base-industrial-center": "このタイルを都市タイルに隣接させて置く。アクション: MCを7支払い、建材生産量+1。",
  "card-base-industrial-microbes": "エネルギー生産量+1、建材生産量+1。",
  "card-base-insulation": "熱生産量を任意の数だけ減らし、同じ数だけMC生産量を増やす。",
  "card-base-interstellar-colony-ship": "科学タグ5個が必要。",
  "card-base-invention-contest": "山札の上から3枚を見る。そのうち1枚を手札に加え、残りの2枚を捨てる。",
  "card-base-inventors-guild": "アクション: 山札の一番上のカードを見て、購入するか捨てるかを選ぶ。",
  "card-base-ironworks": "アクション: エネルギーを4消費して建材を1獲得し、酸素+1%。",
  "card-base-land-claim": "予約されていない場所に自分のマーカーを置く。その場所には自分だけがタイルを置ける。",
  "card-base-large-convoy": "海洋タイルを1枚置き、カードを2枚引く。植物を5獲得、または他のカードに動物を4追加する。",
  "card-base-lava-flows": "気温+2。タルシス・トロルス、アスクレウス山、パボニス山、アルシア山のいずれかにこのタイルを置く。",
  "card-base-lightning-harvest": "科学タグ3個が必要。エネルギー生産量+1、MC生産量+1。",
  "card-base-local-heat-trapping": "熱を5消費して、植物を4獲得、または他のカードに動物を2追加する。",
  "card-base-lunar-beam": "MC生産量-2、熱生産量+2、エネルギー生産量+2。",
  "card-base-mangrove": "気温+4度以上が必要。海洋タイル用に予約された場所に緑地タイルを1枚置き、酸素+1%。通常の設置制限は無視する。",
  "card-base-martian-rails": "アクション: エネルギーを1消費して、火星上の都市タイル1枚につきMCを1獲得。",
  "card-base-media-archives": "全プレイヤーがこれまでにプレイしたイベント1枚につきMCを1獲得。",
  "card-base-media-group": "効果: イベントカードをプレイした後、MCを3獲得。",
  "card-base-mining-area": "建材またはチタンの設置ボーナスがある場所に、自分の他のタイルに隣接させてこのタイルを置く。その資源の生産量+1。",
  "card-base-mining-rights": "建材またはチタンの設置ボーナスがある場所にこのタイルを置く。その生産量+1。",
  "card-base-mohole-area": "熱生産量+4。海洋タイル用に予約された場所にこのタイルを置く。",
  "card-base-natural-preserve": "酸素4%以下が必要。他のどのタイルにも隣接しない場所にこのタイルを置く。MC生産量+1。",
  "card-base-nitrogen-rich-asteroid": "TR+2、気温+1。植物生産量+1。ただし植物タグを3個持っていれば+4。",
  "card-base-nitrophilic-moss": "海洋タイル3枚以上と、植物を2失うことが必要。植物生産量+2。",
  "card-base-noctis-city": "エネルギー生産量-1、MC生産量+3。予約された場所に都市タイルを1枚置く。通常の設置制限は無視する。",
  "card-base-nuclear-zone": "このタイルを置き、気温+2。",
  "card-base-olympus-conference": "このカードを含め、科学タグを持つカードをプレイした際、このカードに科学資源を1追加するか、このカードから科学資源を1除去してカードを1枚引く。",
  "card-base-optimal-aerobraking": "効果: 宇宙イベントをプレイした際、MCを3、熱を3獲得。",
  "card-base-ore-processor": "アクション: エネルギーを4消費してチタンを1獲得し、酸素+1%。",
  "card-base-phobos-space-haven": "チタン生産量+1、予約された場所に都市タイルを1枚置く。",
  "card-base-physics-complex": "アクション: エネルギーを6消費してこのカードに科学資源を1追加する。",
  "card-base-power-grid": "このカードを含め、電力タグ1個につきエネルギー生産量+1。",
  "card-base-power-infrastructure": "アクション: 任意の量のエネルギーを消費して、同じ量のMCを獲得する。",
  "card-base-protected-habitats": "Opponents may not remove your",
  "card-base-protected-valley": "MC生産量+2。海洋タイル用に予約された場所に緑地タイルを1枚置き、通常の設置制限は無視する。酸素+1%。",
  "card-base-regolith-eaters": "アクション: このカードに微生物を1追加する、またはこのカードから微生物を2除去して酸素+1%。",
  "card-base-release-of-inert-gases": "TR+2。",
  "card-base-research": "科学カード2枚をプレイしたものとして扱う。カードを2枚引く。",
  "card-base-research-outpost": "他のどのタイルにも隣接しない場所に都市タイルを1枚置く。効果: カードのコストがMC1下がる。",
  "card-base-robotic-workforce": "自分の建材カード1枚の生産ボックスのみを複製する。",
  "card-base-rover-construction": "効果: 誰かが都市タイルを置いた際、MCを2獲得。",
  "card-base-sabotage": "任意のプレイヤーからチタンを最大3、または建材を4、またはMCを7奪う。",
  "card-base-satellites": "このカードを含め、宇宙タグ1個につきMC生産量+1。",
  "card-base-security-fleet": "アクション: チタンを1消費してこのカードに戦闘資源を1追加する。",
  "card-base-space-mirrors": "アクション: MCを7消費してエネルギー生産量+1。",
  "card-base-space-station": "効果: 宇宙カードをプレイする際、コストが2MC安くなる。",
  "card-base-special-design": "今世代に次にプレイするカードは、グローバル要件を+2または-2ステップまで無視できる。選択は自分次第。",
  "card-base-standard-technology": "効果: 特許売却を除くスタンダードプロジェクトの代金を支払った後、MCを3獲得。",
  "card-base-tardigrades": "アクション: このカードに微生物を1追加する。",
  "card-base-terraforming-ganymede": "ジョビアンタグ1つにつきTR+1（このカードを含む）。",
  "card-base-toll-station": "対戦相手が持つ宇宙タグ1つにつきMC生産量+1。",
  "card-base-towing-a-comet": "植物を2獲得。酸素+1ステップ、海洋タイルを1枚置く。",
  "card-base-tropical-resort": "熱生産量-2。MC生産量+3。",
  "card-base-underground-detonations": "アクション: 10MCを支払い、熱生産量+2。",
  "card-base-urbanized-area": "エネルギー生産量-1。MC生産量+2。他の都市タイル2枚以上に隣接する場所に都市タイルを1枚置く。",
  "card-base-viral-enhancers": "効果: 植物・微生物・動物タグのカードをプレイしたとき（このカードを含む）、植物を1獲得するか、そのカードに資源を1個追加する。",
  "card-base-virus": "任意のプレイヤーから動物を2個まで、または植物を5個まで取り除く。",
  "card-base-water-import-from-europa": "アクション: 12MCを支払い、海洋タイルを1枚置く。宇宙カードをプレイする場合と同様にチタンを使用できる。",
  "card-base-zeppelins": "酸素5%以上が必要。火星上の都市タイル1枚につきMC生産量+1。",
  "card-colonies-air-raid": "フローターを1個失う必要がある。任意のプレイヤーから5MCを奪う。",
  "card-colonies-arklight": "45MCを所持した状態で開始する。MC生産量+2。このカードにある動物2個につき1勝利点。",
  "card-colonies-community-services": "タグを持たないカード1枚につきMC生産量+1（このカードを含む）。",
  "card-colonies-ecology-research": "所有する植民地1つにつき植物生産量+1。他のカード1枚に動物を1個、別の他のカード1枚に微生物を2個追加する。",
  "card-colonies-floater-leasing": "所持するフローター3個につきMC生産量+1。",
  "card-colonies-floater-technology": "アクション: 他のカードにフローターを1個追加する。",
  "card-colonies-galilean-waystation": "場に出ているジョビアンタグ1つにつきMC生産量+1。",
  "card-colonies-heavy-taxation": "地球タグ2つが必要。MC生産量+2。MCを4獲得。",
  "card-colonies-ice-moon-colony": "植民地を1つ、海洋タイルを1枚置く。",
  "card-colonies-lunar-exports": "植物生産量+2、またはMC生産量+5。",
  "card-colonies-lunar-mining": "場に出ている地球タグ2つにつきチタン生産量+1（このカードを含む）。",
  "card-colonies-market-manipulation": "植民地タイルのトラックを1つ1ステップ上げる。別の植民地タイルのトラックを1ステップ下げる。",
  "card-colonies-martian-zoo": "場に都市タイルが2枚必要。アクション: このカードにある動物1個につきMCを1獲得する。",
  "card-colonies-molecular-printing": "場にある都市タイル1枚につきMCを1獲得。場にある植民地1つにつきMCを1獲得。",
  "card-colonies-nitrogen-from-titan": "TR+2。ジョビアンカードにフローターを2個追加する。",
  "card-colonies-pioneer-settlement": "所持する植民地が1つ以下である必要がある。MC生産量-2。植民地を1つ置く。",
  "card-colonies-productive-outpost": "所有する植民地のボーナスをすべて獲得する。",
  "card-colonies-quantum-communications": "科学タグ4つが必要。場にある植民地1つにつきMC生産量+1。",
  "card-colonies-refugee-camps": "アクション: MC生産量-1で、このカードにキャンプ資源を1個追加する。",
  "card-colonies-research-colony": "植民地を1つ置く。すでに植民地を持つ場所にも置ける。カードを2枚引く。",
  "card-colonies-solar-probe": "所持する科学タグ3つにつきカードを1枚引く（このカードを含む）。",
  "card-colonies-space-port": "植民地1つが必要。エネルギー生産量-1。MC生産量+4。都市タイルを1枚置く。交易船を1隻獲得。",
  "card-colonies-space-port-colony": "植民地が必要。植民地を1つ置く。すでに植民地を持つ植民地タイルにも置ける。交易船を1隻獲得。",
  "card-colonies-sub-zero-salt-fish": "気温-6°C以上が必要。任意の植物生産量-1。アクション: このカードに動物を1個置く。",
  "card-colonies-titan-air-scrapping": "アクション: チタンを1消費してこのカードにフローターを2個追加する、またはこのカードのフローターを2個消費してTR+1。",
  "card-colonies-titan-floating-launch-pad": "任意のジョビアンカードにフローターを2個追加する。",
  "card-colonies-titan-shuttles": "アクション: 任意のジョビアンカードにフローターを2個追加する、またはこのカードのフローターを任意数消費して同数のチタンを獲得する。",
  "card-colonies-trade-envoys": "効果: 交易を行うとき、先にその植民地タイルのトラックを1ステップ上げてもよい。",
  "card-colonies-urban-decomposers": "場に都市タイル1枚と植民地1つを持つ必要がある。植物生産量+1。他のカードに微生物を2個追加する。",
  "card-prelude-lava-tube-settlement": "エネルギー生産量-1。MC生産量+2。隣接都市の制限なく火山地帯に都市タイルを1枚置く。",
  "card-prelude-psychrophiles": "気温が-20°C以下である必要がある。アクション: このカードに微生物を1個置く。",
  "card-prelude-research-coordination": "プレイ後、アクションを実行する際、ワイルドタグは任意のタグ1つとして扱える。",
  "card-prelude2-applied-science": "ここに科学資源を6個加える。アクション: このカードの科学資源1個を支払って好きな標準資源を1個獲得する、またはこのカードの科学資源1個を支払って資源を置ける任意のカードに資源を1個置く。",
  "card-prelude2-atmospheric-enhancers": "気温+2、または酸素+2、または金星+2。フローターのアイコンが付いたカードを2枚引く。",
  "card-prelude2-board-of-directors": "ここにディレクター資源を4個加える。",
  "card-prelude2-ceres-tech-market": "アクション: 手札から任意の枚数のカードを捨て、捨てたカード1枚につきMCを2獲得する。",
  "card-prelude2-cloud-tourism": "所有する地球タグと金星タグの組1組につきMC生産量+1。このカードのフローターが3個増える。アクション: このカードにフローターを1個置く。",
  "card-prelude2-colonial-envoys": "Unityが与党であるか、Unityに代表者を2人送っている必要がある。所有する植民地1つにつき代表者を1人配置する。別々の政党に配置してもよい。",
  "card-prelude2-colonial-representation": "所有する植民地1つにつきMCを3獲得。",
  "card-prelude2-corridors-of-power": "効果: 党首になるたび、1枚引く。TR+1、MCを4獲得。",
  "card-prelude2-floating-refinery": "所有する金星タグ1つにつきこのカードにフローターを1個追加する。",
  "card-prelude2-floating-trade-hub": "アクション: 任意のカードにフローターを2個加える、またはここにあるフローターを任意の数取り除き、同数の標準資源を1種類獲得する。",
  "card-prelude2-focused-organization": "アクション: カードを1枚捨てて標準資源を1個消費し、1枚引いて標準資源を1個獲得する。1枚引いて標準資源を1個獲得する。",
  "card-prelude2-frontier-town": "Mars Firstが与党であるか、Mars Firstに代表者を2人送っている必要がある。エネルギー生産量-1。都市タイルを1枚置く。配置ボーナスをさらに2回追加で獲得する。",
  "card-prelude2-ghg-shipment": "Kelvinistsが与党であるか、Kelvinistsに代表者を2人送っている必要がある。熱生産量+1。所持するフローター1個につき熱を1獲得。",
  "card-prelude2-high-circles": "TR+1し、党の要件があるカードを1枚引く。1つの党に代表者を2人配置する。効果: 影響力+1。",
  "card-prelude2-industrial-complex": "MCを18失う。1未満のすべての生産量を1にする。",
  "card-prelude2-ishtar-expedition": "金星10%以上が必要。チタンを3獲得し、金星カードを2枚引く。",
  "card-prelude2-l1-trade-terminal": "効果: 交易を行うとき、先にその植民地タイルのトラックを2ステップ上げてもよい。",
  "card-prelude2-main-belt-asteroids": "MCを5失う。ここにある小惑星2個につき1勝利点。アクション: 任意のカードに小惑星を1個置く。",
  "card-prelude2-microgravity-nutrition": "所有する植民地1つにつきMC生産量+1。",
  "card-prelude2-nirgal-enterprises": "30MCを所持した状態で開始する。エネルギー生産量、植物生産量、建材生産量をそれぞれ+1。",
  "card-prelude2-nobel-prize": "MCを5獲得。要件のあるカードを2枚引く。",
  "card-prelude2-old-mining-colony": "チタン生産量+1。植民地を1個配置する。カードを1枚捨てる。",
  "card-prelude2-planetary-alliance": "TR+2。ジョビアンカードを1枚と金星カードを1枚引く。",
  "card-prelude2-project-eden": "海洋タイルを1枚、都市タイルを1枚、緑地タイルを1枚置く。カードを3枚捨てる。",
  "card-prelude2-recession": "各対戦相手はMCを5失い、MC生産量-1。あなたはMCを10獲得する。",
  "card-prelude2-red-appeasement": "Redsが与党であるか、Redsに代表者を2人送っており、かつ他のプレイヤーが誰もパスしていない必要がある。MC生産量+2。これはパスとして扱われる。今世代、これ以上のターンは行えない。",
  "card-prelude2-rise-to-power": "MC生産量+3。代表者を3人配置する。異なる党に分けて配置してもよい。",
  "card-prelude2-sagitta-frontier-services": "31MCを所持した状態で開始する。エネルギー生産量+1、MC生産量+2。タグを持たないカードを1枚引く。",
  "card-prelude2-soil-bacteria": "微生物カードを2枚引き、植物を3獲得。",
  "card-prelude2-soil-studies": "気温-4°C以下である必要がある。所有する金星タグ、植物タグ、植民地1つにつき植物を1獲得。",
  "card-prelude2-special-permit": "Greensが与党であるか、Greensに代表者を2人送っている必要がある。任意のプレイヤーから植物を4個奪う。",
  "card-prelude2-spire": "50MCを所持した状態で開始する。最初のアクションとして4枚引き、手札から3枚捨てる。効果: このカードを含め2つ以上のタグを持つカードをプレイするたび、ここに科学資源を1個加える。効果: 標準プロジェクトの支払いをするとき、ここにある科学資源はそれぞれMC2として使用できる。",
  "card-prelude2-sponsoring-nation": "地球タグ4つが必要。TRを3獲得。代表者を2人配置する。",
  "card-prelude2-stratospheric-expedition": "任意のカードにフローターを2個追加する。金星カードを2枚引く。",
  "card-prelude2-summit-logistics": "所有する惑星タグと植民地1つにつきMCを1獲得。カードを2枚引く。",
  "card-prelude2-terraforming-deal": "効果: TRが上がるたび、その1段階ごとにMCを2獲得。",
  "card-prelude2-unexpected-application": "カードを1枚捨てて金星テラフォームを1ステップ進める。",
  "card-prelude2-venus-allies": "金星+2ステップ。所有する植民地1つにつきMCを4獲得。",
  "card-prelude2-venus-contract": "金星カードを1枚引く。TR+1。",
  "card-prelude2-venus-orbital-survey": "アクション: 山札の上から2枚を公開し、金星カードは無料で手札に加える。それ以外のカードは購入するか捨てる。",
  "card-prelude2-venus-shuttles": "任意の金星カードにフローターを2個追加する。",
  "card-prelude2-wg-project": "議長である必要がある。プレリュードカードを3枚引いてそのうち1枚をプレイし、残り2枚は捨てる。",
  "card-promo-advertising": "効果: 基本コスト20MC以上のカードをプレイしたとき、MC生産量+1。",
  "card-promo-aqueduct-systems": "海洋に隣接する都市を持つ必要がある。建材タグ付きのカードを3枚引く。",
  "card-promo-asteroid-deflection-system": "エネルギー生産量-1。このカードの小惑星資源1個につき勝利点1点。",
  "card-promo-asteroid-hollowing": "アクション: チタンを1消費してこのカードに小惑星資源を1個追加し、MC生産量+1。",
  "card-promo-asteroid-rights": "アクション: MCを1消費して任意のカードに小惑星を1個追加する、またはこのカードの小惑星を1個消費してMC生産量+1するかチタンを2獲得する。このカードに小惑星を2個追加する。",
  "card-promo-astra-mechanica": "プレイ済みのイベントカードを2枚まで手札に戻す。ただし特殊タイルを置くカードは対象外。",
  "card-promo-astrodrill": "35MCと小惑星資源3個を所持した状態で開始する。",
  "card-promo-bactoviral-research": "カードを1枚引く。プレイ済みのカードから1枚を選び、所持する科学タグ1つにつき微生物を1個追加する（このカードを含む）。",
  "card-promo-bio-printing-facility": "アクション: エネルギーを2消費して植物を2獲得する、または他のカードに動物を1個追加する。",
  "card-promo-carbon-nanosystems": "効果: 科学タグのカードをプレイしたとき（このカードを含む）、このカードにグラフェン資源を1個追加する。効果: 宇宙タグまたは都市タグのカードをプレイする際、グラフェン1個につきMC4として使用できる。",
  "card-promo-casinos": "都市を持つ必要がある。エネルギー生産量-1。MC生産量+4。",
  "card-promo-city-parks": "都市を3つ持つ必要がある。植物を2獲得。",
  "card-promo-comet-aiming": "アクション: チタンを1消費して任意のカードに小惑星資源を1個追加する、またはこのカードの小惑星を1個取り除いて海洋タイルを1枚置く。",
  "card-promo-crash-site-cleanup": "今世代、他のプレイヤーの植物が取り除かれている必要がある。チタンを1、または建材を2獲得。",
  "card-promo-cutting-edge-technology": "効果: 条件のあるカードをプレイする際、コストが2MC安くなる。",
  "card-promo-cyberia-systems": "建材生産量+1。建材タグを持つ自分のカード2枚の生産ボックスをコピーする。",
  "card-promo-deimos-down-promo": "気温+3。建材を4獲得。このタイルはどの都市タイルにも隣接しない場所に置く。任意のプレイヤーから植物を6個まで取り除く。",
  "card-promo-directed-heat-usage": "アクション: 熱を3消費してMCを4、または植物を2獲得する。",
  "card-promo-directed-impactors": "アクション: MCを6消費して任意のカードに小惑星を1個追加する（この支払いにチタンを使用してもよい）、またはこのカードの小惑星を1個取り除いて気温+1。",
  "card-promo-diversity-support": "9種類の異なる資源を持っていることが必要。TRを1獲得。",
  "card-promo-double-down": "もう1枚のPreludeの直接効果をコピーする。",
  "card-promo-dusk-laser-mining": "科学タグ2個が必要。エネルギー生産量-1、チタン生産量+1。チタンを4獲得。",
  "card-promo-energy-market": "アクション: MCを2X支払ってエネルギーをX獲得、またはエネルギー生産量-1でMCを8獲得。",
  "card-promo-established-methods": "MCを30獲得。その後、標準プロジェクトを2つ支払って実行する。",
  "card-promo-field-capped-city": "MC生産量+2。エネルギー生産量+1。植物を3獲得。都市タイルを1枚置く。",
  "card-promo-floyd-continuum": "アクション: 完了したテラフォーミングパラメータ1つにつきMCを3獲得。",
  "card-promo-great-dam-promo": "海洋タイル4枚が必要。エネルギー生産量+2。このタイルは海洋タイルに隣接して置く。",
  "card-promo-harvest": "緑地タイルを3枚持っていることが必要。MCを12獲得。",
  "card-promo-head-start": "建材を2獲得。手札にあるプロジェクトカード1枚につきMCを2獲得。",
  "card-promo-hermetic-order-of-mars": "酸素4%以下が必要。MC生産量+2。自分のタイルに隣接する空きエリア1つにつきMCを1獲得。",
  "card-promo-hi-tech-lab": "アクション: 任意の枚数のエネルギーを支払い、同じ枚数のカードを引く。そのうち1枚を手札に加え、残りは捨てる。",
  "card-promo-icy-impactors": "アクション: MC10（チタンで支払い可）を支払いこのカードに小惑星を2個追加、またはこのカードの小惑星1個を支払い海洋タイルを1枚置く。この場合、置く場所は先手プレイヤーが指定する。",
  "card-promo-imported-nutrients": "植物を4獲得し、他の1枚のカードに微生物を4個追加する。",
  "card-promo-interplanetary-trade": "このカードを含め、場に出ている異なるタグ1種類につきMC生産量+1。",
  "card-promo-kaguya-tech": "MC生産量+2。カードを1枚引く。自分の緑地タイル1枚を取り除く（酸素には影響しない）。配置ルールを無視してそこに都市タイルを置く。通常どおり配置ボーナスを獲得する。",
  "card-promo-law-suit": "このゲネレーション中に自分の資源を奪う、または自分の生産量を減少させたプレイヤーからMCを3奪う。このカードはそのプレイヤーのイベント置き場に裏向きで置く。",
  "card-promo-mars-nomads": "アクション: 遊牧民コマを隣接する未予約の空きエリアに移動し、そこに特殊タイルを置いたときと同様の配置ボーナスを獲得する。遊牧民コマのあるエリアにはタイルを置けない。遊牧民コマはゲームボード上の未予約の空きエリアに置く。",
  "card-promo-martian-lumber-corp": "効果: 建材タグのカードをプレイする際、植物1個をMC3として使用できる。",
  "card-promo-meat-industry": "効果: 任意のカードに動物を獲得するたびMCを2獲得。",
  "card-promo-meltworks": "アクション: 熱5を支払い建材を3獲得。",
  "card-promo-merger": "企業カードを4枚引く。そのうち1枚をプレイし、残り3枚を捨てる。その後、MCを42支払う。",
  "card-promo-mohole-lake": "植物を3獲得。気温+1。海洋タイルを1枚置く。アクション: 他のカードに微生物を1個置く、または他のカードに動物を1個置く。",
  "card-promo-mons-insurance": "48MCを所持した状態で開始する。MC生産量+4。全対戦相手のMC生産量-2。これによって以下の効果はトリガーされない。",
  "card-promo-neptunian-power-consultants": "このカードにある水力発電資源1個につき勝利点1点。",
  "card-promo-new-holland": "火星上に都市タイル4枚が必要。MC生産量+3。通常の都市配置制限に従い、既に置かれている海洋タイルの上に都市タイルを置く。このタイルは都市かつ海洋として扱う。",
  "card-promo-new-partner": "MC生産量+1。すぐにPreludeカードを2枚引く。そのうち1枚をプレイし、残りを捨てる。",
  "card-promo-outdoor-sports": "海洋タイルに隣接する都市が必要。MC生産量+2。",
  "card-promo-pharmacy-union": "効果: 微生物タグを持つカードがプレイされるたび、ここに疾病を1個加え、MCを4、または可能な限り失う。科学タグをプレイしたとき、ここから疾病を1個取り除きTRを1獲得する。または、ここに疾病がない場合、このカードを裏向きにしてイベントの山に置き、TRを3獲得してもよい。",
  "card-promo-potatoes": "植物を2失う。MC生産量+2。",
  "card-promo-project-inspection": "このゲネレーション中に使用済みのカードアクションを使用する。",
  "card-promo-protected-growth": "酸素7%以下が必要。自分の電力タグ1個につき植物を1獲得。",
  "card-promo-public-plans": "手札から任意の枚数の他のカードを公開する（対戦相手はそれらを確認できる）。公開したカード1枚につきMCを1獲得。",
  "card-promo-recyclon": "38MCと建材生産量1を所持した状態で開始する。",
  "card-promo-rego-plastics": "効果: 自分の建材資源の価値がMC1追加される。",
  "card-promo-robot-pollinators": "酸素4%が必要。植物生産量+1。自分の植物タグ1個につき植物を1獲得。",
  "card-promo-saturn-surfing": "このカードを含め、自分の地球タグ1個につきフローターを1個追加する。アクション: このカードのフローターを1個支払い、このカードにあるフローター1個につきMCを1獲得する（最大5）。",
  "card-promo-self-replicating-robots": "科学タグ2個が必要。手札から宇宙タグまたは建材タグのカードを1枚公開してこのカードの上に置き、資源を2個追加する。またはこのカードにあるカードの資源を倍にする。",
  "card-promo-snow-algae": "海洋タイル2枚が必要。植物生産量+1、熱生産量+1。",
  "card-promo-soil-enrichment": "自分の任意のカードから微生物1個を支払い、植物を5獲得。",
  "card-promo-splice": "44MCを所持した状態で開始する。最初のアクションとして、微生物タグのカードを1枚公開するまでカードを公開し続ける。それを手札に加え、残りは捨てる。",
  "card-promo-st-joseph-of-cupertino-mission": "大聖堂のある都市1つにつき勝利点1点。",
  "card-promo-stanford-torus": "惑星の外、独立した位置に都市タイルを1枚置く。",
  "card-promo-static-harvesting": "海洋タイル3枚以下が必要。エネルギー生産量+1。自分の建材タグ1個につきMCを1獲得。",
  "card-promo-strategic-base-planning": "MCを3支払う。都市タイルを1枚置く。植民地を1個配置する。",
  "card-promo-vermin": "ここに動物が10個以上いる場合、自分を含む各プレイヤーは所有する都市1つにつき勝利点-1。アクション: このカードに動物を1個置く、または任意のカードに微生物を1個置く。",
  "card-turmoil-aerial-lenses": "ケルビニストが与党であるか、そこに代表者を2人置いていることが必要。任意のプレイヤーから植物を最大2個取り除く。熱生産量+2。",
  "card-turmoil-banned-delegate": "自分が議長であることが必要。党首以外の代表者を1人取り除く。",
  "card-turmoil-cultural-metropolis": "ユニティが与党であるか、そこに代表者を2人置いていることが必要。エネルギー生産量-1、MC生産量+3。都市タイルを1枚置く。1つの政党に代表者を2人置く。",
  "card-turmoil-diaspora-movement": "レッズが与党であるか、そこに代表者を2人置いていることが必要。このカードを含め、場に出ているジョビアンタグ1個につきMCを1獲得。",
  "card-turmoil-event-analysts": "サイエンティストが与党であるか、そこに代表者を2人置いていることが必要。",
  "card-turmoil-gmo-contract": "グリーンズが与党であるか、そこに代表者を2人置いていることが必要。",
  "card-turmoil-martian-media-center": "マーズファーストが与党であるか、そこに代表者を2人置いていることが必要。MC生産量+2。アクション: MCを3支払い、代表者を1人配置する。",
  "card-turmoil-parliament-hall": "マーズファーストが与党であるか、そこに代表者を2人置いていることが必要。このカードを含め、建材タグ3個につきMC生産量+1。",
  "card-turmoil-political-alliance": "党首を2人持っていることが必要。TRを1獲得。",
  "card-turmoil-pr-office": "ユニティが与党であるか、そこに代表者を2人置いていることが必要。TRを1獲得。このカードを含め、自分の地球タグ1個につきMCを1獲得。",
  "card-turmoil-pristar": "53MCを所持した状態で開始する。TR-2。ここにある保護資源1個につき1勝利点。",
  "card-turmoil-recruitment": "中立の党首以外の代表者1人を、予備から自分の代表者1人と交換する。",
  "card-turmoil-red-tourism-wave": "レッズが与党であるか、そこに代表者を2人置いていることが必要。自分のタイルに隣接する空きエリア1つにつきMCを1獲得。",
  "card-turmoil-septem-tribus": "36MCを所持した状態で開始する。アクションを行うとき、ワイルドタグは任意のタグ1つとして扱う。",
  "card-turmoil-sponsored-mohole": "ケルビニストが与党であるか、そこに代表者を2人置いていることが必要。熱生産量+2。",
  "card-turmoil-supported-research": "サイエンティストが与党であるか、そこに代表者を2人置いていることが必要。カードを2枚引く。",
  "card-turmoil-terralabs-research": "14MCを所持した状態で開始する。TR-1。",
  "card-turmoil-utopia-invest": "40MCを所持した状態で開始する。建材生産量とチタン生産量をそれぞれ+1。",
  "card-turmoil-vote-of-no-confidence": "いずれかの政党に党首を持っていて、現在の議長が中立であることが必要。中立の議長を取り除き、代わりに予備から自分の代表者をそこに置く。TRを1獲得。",
  "card-turmoil-wildlife-dome": "グリーンズが与党であるか、そこに代表者を2人置いていることが必要。緑地タイルを1枚置き、酸素+1。",
  "card-venus-aerial-mappers": "アクション: 任意のカードにフローターを1個追加する、またはこのカードのフローター1個を支払いカードを1枚引く。",
  "card-venus-aerosport-tournament": "フローターを5個持っていることが必要。場に出ている都市タイル1枚につきMCを1獲得。",
  "card-venus-air-scrapping-expedition": "金星+1。任意の金星カードにフローターを3個追加する。",
  "card-venus-aphrodite": "植物生産量1と47MCを所持した状態で開始する。",
  "card-venus-atmoscoop": "科学タグ3個が必要。気温+2、または金星+2のいずれかを選ぶ。任意のカードにフローターを2個追加する。",
  "card-venus-celestic": "42MCを所持した状態で開始する。最初のアクションとして、フローターのアイコンが付いたカードを2枚公開するまで山札からカードを公開し続ける。それらを手札に加え、残りは捨てる。",
  "card-venus-comet-for-venus": "金星+1。場に金星タグを持つ任意のプレイヤーからMCを最大4奪う。",
  "card-venus-corroder-suits": "MC生産量+2。任意の金星カードに資源を1個追加する。",
  "card-venus-deuterium-export": "アクション: このカードにフローターを1個追加する、またはこのカードのフローター1個を支払いエネルギー生産量+1。",
  "card-venus-dirigibles": "アクション: 任意のカードにフローターを1個追加する。効果: 金星タグをプレイする際、このカードのフローターを支払いに使用でき、各1個につきMC3として扱う。",
  "card-venus-extractor-balloons": "アクション: このカードにフローターを1個追加する、またはこのカードのフローター2個を取り除き金星+1。その後このカードにフローターを3個追加する。",
  "card-venus-forced-precipitation": "アクション: MCを2支払いこのカードにフローターを1個追加する、またはこのカードのフローター2個を支払い金星+1。",
  "card-venus-freyja-biodomes": "金星トラック10%以上が必要。他の金星カードに微生物2個または動物2個を追加する。エネルギー生産量-1、MC生産量+2。",
  "card-venus-gyropolis": "エネルギー生産量-2。自分の金星タグと地球タグ1個につきMC生産量+1。都市タイルを1枚置く。",
  "card-venus-hydrogen-to-venus": "金星+1。自分のジョビアンタグ1個につき、いずれかの金星カードにフローターを1個追加する。",
  "card-venus-io-sulphur-research": "カードを1枚引く。金星タグを3個以上持っている場合は3枚引く。",
  "card-venus-jet-stream-microscrappers": "アクション: チタン1を支払いこのカードにフローターを2個追加する、またはこのカードのフローター2個を支払い金星+1。",
  "card-venus-local-shading": "アクション: このカードにフローターを1個追加する、またはこのカードのフローター1個を支払いMC生産量+1。",
  "card-venus-luxury-foods": "金星タグ、地球タグ、ジョビアンタグをそれぞれ持っていることが必要。",
  "card-venus-manutech": "建材生産量1と35MCを所持した状態で開始する。",
  "card-venus-morning-star-inc": "50MCを所持した状態で開始する。最初のアクションとして、金星タグのカードを3枚公開するまで山札からカードを公開し続ける。それらを手札に加え、残りは捨てる。",
  "card-venus-neutralizer-factory": "金星10%が必要。金星トラック+1。",
  "card-venus-rotator-impacts": "金星14%以下が必要。アクション: このカードの小惑星1個を取り除いて金星を1段階上げる、またはMCを6支払ってこのカードに小惑星を1個置く。",
  "card-venus-sister-planet-support": "金星タグと地球タグが必要。MC生産量+3。",
  "card-venus-spin-inducing-asteroid": "金星10%以下が必要。金星+2。",
  "card-venus-sponsored-academies": "手札からカードを1枚捨て、その後カードを3枚引く。すべての対戦相手はカードを1枚引く。",
  "card-venus-stratospheric-birds": "金星12%が必要。かつ任意のカードのフローター1個を支払う。アクション: このカードに動物を1個置く。",
  "card-venus-terraforming-contract": "TRが25以上必要。MC生産量+4。",
  "card-venus-venusian-plants": "金星16%が必要。金星+1。他の金星カードに微生物1個または動物1個を追加する。",
  "corp-point-luna": "チタン生産量+1。地球タグをプレイするたび1枚引く。",
  "corp-saturn": "Jovianタグが場に出るたびMC生産量+1。",
  "corp-teractor": "Earthタグのカードコスト-3。",
  "corp-thorgate": "エネルギー生産量+1。Powerタグのカードコスト-3。",
  "corp-valley-trust": "最初のアクションでPreludeを3枚見て1枚プレイする。科学タグのカードコスト-2。",
  "global-aquifer-released-by-public-council": "第1プレイヤーが海洋タイルを1枚置く。影響力1につき植物1と建材1を獲得。",
  "global-asteroid-mining": "ジョビアンタグ1つにつき(最大5)チタンを1獲得、および影響力1につきチタンを1獲得。",
  "global-celebrity-leaders": "プレイされたイベント1枚につき(最大5)MCを2獲得、および影響力1につきMCを2獲得。",
  "global-cloud-societies": "フローターを収集できるすべてのカードにフローターを1個ずつ加える。影響力1につきカード1枚にフローターを1個加える。",
  "global-corrosive-rain": "カードからフローターを2個失う、またはMCを10失う。影響力1につき1枚引く。",
  "global-diversity": "異なるタグを9種類以上持っていればMCを10獲得。影響力は固有タグとして数える。",
  "global-dry-deserts": "第1プレイヤーがゲームボードから海洋タイルを1枚取り除く。影響力1につき標準資源を1個獲得。",
  "global-eco-sabotage": "3+影響力を超える植物をすべて失う。",
  "global-election": "影響力に建材タグと都市タイルの数を加えて数える(上限なし)。最も多いプレイヤー(ソロの場合は10以上)はTR+2、2番目に多いプレイヤー(ソロの場合は5以上)はTR+1(同点の場合は両方獲得)。",
  "global-generous-funding": "影響力1につき、およびTRが15を超えて5刻みで到達するごとに(最大5セット)MCを2獲得。",
  "global-global-dust-storm": "熱をすべて失う。建材タグ1つにつき(最大5、その後影響力分軽減)MCを2失う。",
  "global-homeworld-support": "地球タグ1つにつき(最大5)MCを2獲得、および影響力1につきMCを2獲得。",
  "global-improved-energy-templates": "電力タグ2つにつきエネルギー生産量+1(上限なし)。影響力は電力タグとして数える。",
  "global-interplanetary-trade": "宇宙タグ1つにつき(最大5)MCを2獲得、および影響力1につきMCを2獲得。",
  "global-jovian-tax-rights": "植民地1個につきMC生産量+1。影響力1につきチタンを1獲得。",
  "global-microgravity-health-problems": "植民地1個につき(最大5、その後影響力分軽減)MCを3失う。",
  "global-miners-on-strike": "ジョビアンタグ1つにつき(最大5、その後影響力分軽減)チタンを1失う。",
  "global-mud-slides": "海洋タイルに隣接するタイル1枚につき(最大5、その後影響力分軽減)MCを4失う。",
  "global-pandemic": "建材タグ1つにつき(最大5、その後影響力分軽減)MCを3失う。",
  "global-paradigm-breakdown": "手札からカードを2枚捨てる。影響力1につきMCを2獲得。",
  "global-productivity": "建材生産量1につき(最大5)建材を1獲得、および影響力1につき建材を1獲得。",
  "global-red-influence": "TRが10を超えて5刻みで到達するごとに(最大5セット)MCを3失う。影響力1につきMC生産量+1。",
  "global-revolution": "地球タグの数に影響力を加えて数える。最も多いプレイヤー(1以上)はTR-2、2番目に多いプレイヤー(1以上)はTR-1。ソロ: 合計が4以上ならTR-2。",
  "global-riots": "都市タイル1枚につき(最大5、その後影響力分軽減)MCを4失う。",
  "global-sabotage": "建材生産量とエネルギー生産量をそれぞれ-1。影響力1につき建材を1獲得。",
  "global-scientific-community": "手札のカード1枚につき(上限なし)MCを1獲得、および影響力1につきMCを1獲得。",
  "global-snow-cover": "気温-2。影響力1につき1枚引く。",
  "global-solar-flare": "宇宙タグ1つにつき(最大5、その後影響力分軽減)MCを3失う。",
  "global-solarnet-shutdown": "青いカード1枚につき(最大5、その後影響力分軽減)MCを3失う。",
  "global-spin-off-products": "科学タグ1つにつき(最大5)MCを2獲得、および影響力1につきMCを2獲得。",
  "global-sponsored-projects": "資源が置かれているすべてのカードに資源を1個加える。影響力1につき1枚引く。",
  "global-strong-society": "都市タイル1枚につき(最大5)MCを2獲得、および影響力1につきMCを2獲得。",
  "global-successful-organisms": "植物生産量1につき(最大5)植物を1獲得、および影響力1につき植物を1獲得。",
  "global-venus-infrastructure": "金星タグ1つにつき(最大5)MCを2獲得、および影響力1につきMCを2獲得。",
  "global-volcanic-eruptions": "気温+2。影響力1につき熱生産量+1。",
  "global-war-on-earth": "TR-4。影響力1につき1段階分軽減される。",
  "prelude-acquired-space-agency": "チタン6、山札から宇宙タグ2枚を手札へ。"
};
